name: "Update RSV Target Data"

on:
  workflow_dispatch:
    inputs:
      nssp_update_local:
        description: "Update NSSP data from the Hub-hosted raw data file?"
        type: boolean
        default: true
  schedule:
    - cron: "00 17 * * 3" # run every Wednesday at 5:00 PM UTC (1:00 PM EST)

jobs:
  update-target-data:
    if: ${{ github.repository_owner == 'CDCgov' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: "Generate Installation Token"
      id: get_token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.CDCGOV_HUB_BOT_APP_ID }}
        private-key: ${{ secrets.CDCGOV_HUB_BOT_APP_KEY }}

    - name: "Checkout Code"
      uses: actions/checkout@v6

    - name: "Set Up hubhelpr"
      uses: cdcgov/hubhelpr/actions/setup-hubhelpr@main

    - name: "Update Target Data"
      uses: cdcgov/hubhelpr/actions/update-target-data@main
      with:
        disease: "rsv"
        github_token: ${{ steps.get_token.outputs.token }}
        api_key_id: ${{ secrets.DATA_CDC_GOV_API_KEY_ID }}
        api_key_secret: ${{ secrets.DATA_CDC_GOV_API_KEY_SECRET }}
        nssp_update_local: ${{ inputs.nssp_update_local || 'true' }}
